#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from dvbs2adduceremecum.the_baton import ModCod, Conf, user_bits_per_hertz, MOD_ORDERS, LDPC_RATES


ROLL_OFF = 0.2


def md_table(conf):

    table = conf.__repr__()
    table += '\n'
    table += '\n'
    

    table += '|   |'

    for rate in LDPC_RATES:
        table += '\t%1d /%2d |' % (rate.numerator, rate.denominator)

    table += '\n'

    table += '| - |'

    for rate in LDPC_RATES:
        table += '\t----- |'

    table += '\n'

    for order in MOD_ORDERS:
        table += '| %1d |' % order
        for rate in LDPC_RATES:
            try:
                modcod = ModCod(order, rate)
                eff = user_bits_per_hertz(modcod, conf)
                table += '\t%1.3f |' % eff
            except ValueError as ve:
                table += '\t      |'
        table += '\n'

    return table


print(md_table(Conf(pilots=False, short_frame=False, roll_off=ROLL_OFF)))
print(md_table(Conf(pilots=True,  short_frame=False, roll_off=ROLL_OFF)))
print(md_table(Conf(pilots=False, short_frame=True,  roll_off=ROLL_OFF)))
print(md_table(Conf(pilots=True,  short_frame=True,  roll_off=ROLL_OFF)))
