#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from dvbs2adduceremecum.the_baton import ModCod, Conf, user_bits_per_hertz, MOD_ORDERS, LDPC_RATES


PILOTS = False
SHORT_FRAME = False
ROLL_OFF = 0.2
conf = Conf(PILOTS, SHORT_FRAME, ROLL_OFF)


def eff_wrapper(modcod, conf):
    eff = 0
    try:
        eff = user_bits_per_hertz(modcod, conf)
    except ValueError as e:
        eff = 0

    return eff

print(conf)

table = '|   |'

for rate in LDPC_RATES:
    table += '\t%1d /%2d |' % (rate.numerator, rate.denominator)

table += '\n'

table += '| - |'

for rate in LDPC_RATES:
    table += '\t----- |'

table += '\n'

for order in MOD_ORDERS:
    table += '| %1d |' % order
    for rate in LDPC_RATES:
        eff = eff_wrapper(ModCod(order, rate), conf)
        table += '\t%1.3f |' % eff
    table += '\n'

print(table)
